### ISSUE TITLE
LNK1181	cannot open input file '..\Release\Gpufit.lib'

### ISSUE THREAD

**Issue by jdanial** [gpufit/Gpufit#82] opened 2020-09-29 11:49 UTC
Hi all,

I am thoroughly impressed by the amount of work done with the Gpufit code. I am currently trying to compile it on VS 2019 and it gives me an error that it cannot open the Gpufit.lib file [Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file '..\Release\Gpufit.lib'	GpufitCudaAvailableMex	C:\Sources\Gpufit-build-64\Gpufit\matlab\LINK	1	
]. 

Any ideas why this might be happening and how to resolve that issue.

Best wishes, John.

**Comment by HarvardPaleomag** [comment] 2020-11-24 14:48
Hey, did you figure out what the issue is? I am having the same problem, compiling.
Mike

**Comment by superchromix** [comment] 2020-11-24 15:15
This looks to me like an issue with the CMake file, but I don't have VS2019 installed at the moment to try debugging it...

**Comment by jkfindeisen** [comment] 2021-06-09 07:58
I just did a fresh build of Gpufit with VS 2019 and did not get such an error. Therefore, I cannot reproduce the bug. A quick search for LNK1181 gave that it might be connected to spaces in some file paths, but it does not seem like this is the case here (you seem to build in C;:\Sources\Gpufit-build-64.

Please try again with a clean build directory and follow the instructions. If the error persists one can try to do more. If I don't hear back within some time, I would just close the issue for now. Feel free to comment further at any time.

**Closed as completed** 2021-08-25 11:25 UTC
Labels: bug
