### ISSUE TITLE
Large vectors not supported by MEX library

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#7] opened 2017-01-06 20:33 UTC
When I try to run 10^8 fits at size 5x5, I get the following error in Matlab:

Unexpected Standard exception from MEX file.
What() is:vector<T> too long

Error in GpuFit (line 39)
    data,...

I suspect this is to do with MEX using 32-bit array indexing by default, even for code which is compiled for 64-bit architectures.  The issue is discussed in the link below.  I think the solution is to compile the MEX code with the "-largeArrayDims" flag.

http://de.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html?requestedDomain=www.mathworks.com

This is an important issue because we can't run large numbers of fits at the moment.

**Comment by adrianjp88** [comment] 2017-01-07 07:06
It is not possible to solve this problem on SuperGPU1 since its RAM memory is limited to 8GB.

**Comment by superchromix** [comment] 2017-01-07 11:50
Regardless of the amount of RAM, it is still possible to add the compiler flag.

**Comment by adrianjp88** [comment] 2017-01-07 13:58
I assume, that the flag "-largeArrayDims" must be set when the mex-file is compiled from Matlab using the command mex. I have checked the sizes used in the mex function by printing sizeof(mwSize) and sizeof(mwIndex). Both variables have the length of 64 bit. I also found and removed the unused integer variable data_size defined within the mex function to the value of n_points*n_fits. This variable will overflow while running your test.

**Comment by superchromix** [comment] 2017-01-07 14:07
were you able to set the flag?

**Comment by adrianjp88** [comment] 2017-01-07 14:11
No, i didn't find a possibility to set the flag.

**Comment by superchromix** [comment] 2017-01-07 14:18
where is the command to compile the mex file?

**Comment by adrianjp88** [comment] 2017-01-07 14:38
To compile a mex file a CMake flag is set in GPUfit\bindings\matlab\CMakeLists.txt.

**Comment by superchromix** [comment] 2017-01-07 14:48
and how do you add the extra compilation flag ?

**Comment by adrianjp88** [comment] 2017-01-07 16:59
Sorry, I don't know what you mean. I already wrote  that I don't know how to set the flag.

**Comment by superchromix** [comment] 2017-01-07 17:30
I guess that's what you need to find out..

**Comment by adrianjp88** [comment] 2017-01-08 11:06
You can set a compilation flag using the existing command set_target_properties() by setting the CMake property COMPILE_FLAGS. But as I said before, i don't think that this will solve the problem. Did you try to run the test without the variable data_size in the mex function? Since I'm not able to reproduce the error, it is hard for me to fix this bug.

**Comment by superchromix** [comment] 2017-01-08 13:34
did you add this to the cmake file?

**Comment by superchromix** [comment] 2017-01-09 09:56
have you added the flag to the cmake file?

**Comment by superchromix** [comment] 2017-01-09 09:57
the variable data_size is not related to this bug, since the error message specifically says the problem has to do with the length of a <vector>

**Comment by jkfindeisen** [comment] 2017-01-09 11:45
> But as I said before, i don't think that this will solve the problem.

Adrian, why do you think this won't solve the problem? I will just incoporate it in a commit in a few minutes, then Superchromix has to test it and report back. Finally such large number of fits should become a test.

**Comment by adrianjp88** [comment] 2017-01-09 12:01
Since the variables mwSize and mwIndex already have the length of 64 bit, the 64 bit API is used. I tried to insert the compiler flag, but it was ignored.  I agree, that we need this test.

**Comment by superchromix** [comment] 2017-01-09 12:03
I do not understand why it is not possible to insert the compiler flag.

**Comment by superchromix** [comment] 2017-01-09 12:05
Just because mwSize and mwIndex are 64-bit types, this does not 
necessarily mean that the 64-bit API is used.  Actually, those two data 
type are by definition 64-bit.  The compiler flag needs to be set in 
order to ensure that the 64-bit API is actually used.

**Comment by superchromix** [comment] 2017-01-10 15:01
What is happening with this????

**Comment by adrianjp88** [comment] 2017-01-12 13:35
The error occurred because the product of the int variables n_points and n_fits exceeded the maximum int value. The bug is fixed by changing the data types of the variables to std::size_t.

**Closed by adrianjp88** 2017-01-12 13:35 UTC
Labels: bug
