### ISSUE TITLE
Lower/Upper bound

### ISSUE THREAD

**Issue by ehna** [gpufit/Gpufit#43] opened 2018-01-04 03:07 UTC
I am just wondering how can we add lower and upper bounds for parameters. Is there anyways to do so?

**Comment by Superzorg** [comment] 2018-03-07 19:25
We have a similar requirement as well.  For example something similar to the scipy.optimize.curve_fit **bounds** option.  Any information as to whether there is a plan to include this in future versions would be greatly appreciated!

**Comment by simolorenzi** [comment] 2019-02-15 14:05
I have the same need. Is there any possibility to do so?
I could try to implement that feature, but I need to know exactly in which function the iterations of the parameters are done.

**Comment by jkfindeisen** [comment] 2021-06-08 11:42
Duplicate of #61

**Closed as completed by jkfindeisen** 2021-06-08 11:42 UTC
Labels: duplicate, enhancement
