### ISSUE TITLE
Error_Handling failed

### ISSUE THREAD

**Issue by OptSolution** [gpufit/Gpufit#69] opened 2019-01-15 12:26 UTC
only the test failed

My os is ubuntu 16.04 cuda version is 9.2

Running tests...
Test project /home/wangchen/code/Gpufit/build
      Start  1: Gpufit_Test_Error_Handling
 1/10 Test  #1: Gpufit_Test_Error_Handling ..............***Failed    0.15 sec
      Start  2: Gpufit_Test_Linear_Fit_1D
 2/10 Test  #2: Gpufit_Test_Linear_Fit_1D ...............   Passed    0.13 sec
      Start  3: Gpufit_Test_Gauss_Fit_1D
 3/10 Test  #3: Gpufit_Test_Gauss_Fit_1D ................   Passed    0.14 sec
      Start  4: Gpufit_Test_Gauss_Fit_2D
 4/10 Test  #4: Gpufit_Test_Gauss_Fit_2D ................   Passed    0.14 sec
      Start  5: Gpufit_Test_Gauss_Fit_2D_Elliptic
 5/10 Test  #5: Gpufit_Test_Gauss_Fit_2D_Elliptic .......   Passed    0.13 sec
      Start  6: Gpufit_Test_Gauss_Fit_2D_Rotated
 6/10 Test  #6: Gpufit_Test_Gauss_Fit_2D_Rotated ........   Passed    0.13 sec
      Start  7: Gpufit_Test_Cauchy_Fit_2D_Elliptic
 7/10 Test  #7: Gpufit_Test_Cauchy_Fit_2D_Elliptic ......   Passed    0.13 sec
      Start  8: Gpufit_Test_Fletcher_Powell_Helix_Fit
 8/10 Test  #8: Gpufit_Test_Fletcher_Powell_Helix_Fit ...   Passed    0.14 sec
      Start  9: Gpufit_Test_Brown_Dennis_Fit
 9/10 Test  #9: Gpufit_Test_Brown_Dennis_Fit ............   Passed    0.18 sec
      Start 10: Cpufit_Gpufit_Test_Consistency
10/10 Test #10: Cpufit_Gpufit_Test_Consistency ..........   Passed    0.14 sec

90% tests passed, 1 tests failed out of 10

Total Test time (real) =   1.42 sec

The following tests FAILED:
	  1 - Gpufit_Test_Error_Handling (Failed)
Errors while running CTest
Makefile:83: recipe for target 'test' failed
make: *** [test] Error 8
FAIL

**Comment by jkfindeisen** [comment] 2021-08-30 14:59
I cannot reproduce this behavior. For me all tests are passing. Since there was development in the meantime, the error might have been fixed already. I'll close this issue. If you can reproduce it with the current state of the code, please reopen.

**Closed as completed by jkfindeisen** 2021-08-30 14:59 UTC
Labels: OS Linux
