### ISSUE TITLE
Fitting Statistics Output for Matlab Bindings

### ISSUE THREAD

**Issue by stephenalee** [gpufit/Gpufit#66] opened 2018-07-11 19:29 UTC
Thank you for this great fitting package. I was wondering if the fit statistics, other than chi-squares, could be outputted for the matlab bindings. I'd like to calculate confidence intervals on the fits so outputting the hessian would be helpful.

Thanks.

**Comment by jkfindeisen** [comment] 2021-04-14 13:03
Often asked, similar to #81

**Comment by jkfindeisen** [comment] 2021-06-08 11:35
Closed as duplicate of #81 (doesn't matter which way around). Will talk about it in #81.

**Closed as completed by jkfindeisen** 2021-06-08 11:35 UTC
Labels: duplicate, enhancement
